version: '3.8'

services:
  redis:
    container_name: purl_redis 
    image: docker.arvancloud.ir/redis:7
    restart: always
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
