package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/lib/pq"
	"github.com/mohamadafzal06/purl/entity"
)

type Postgres struct {
	db *sql.DB
}

func NewDB(username, password, host, port, dbname string) (Postgres, error) {
	connectionStr := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable",
		os.Getenv("PURL_POSTGRES_USER"),
		os.Getenv("PURL_POSTGRES_PW"),
		os.Getenv("PURL_POSTGRES_HOST"),
		os.Getenv("PURL_POSTGRES_PORT"),
		os.Getenv("PURL_POSTGRES_DBNAME"),
	)
	db, err := sql.Open("postgres", connectionStr)
	if err != nil {
		return Postgres{}, err
	}
	return Postgres{db}, nil
}

func (p Postgres) Ping() error {
	err := p.db.Ping()
	if err != nil {
		log.Fatalf("cannot ping the database: %v\n", err)
		return fmt.Errorf("cannot ping the database: %v\n", err)
	}

	log.Printf("\nPinging DB successfully...\n")

	return nil
}

func (p Postgres) GetLongURL(ctx context.Context, surl entity.URL) (entity.URL, error) {
	row := p.db.QueryRowContext(ctx, "select url from ulrs where key=$1", surl.Key)
	if err := row.Err(); err != nil {
		// TODO: change the return value witht another entity.URL
		return surl, fmt.Errorf("cannot retrieve this url: %w\n", err)
	}

	var lurl entity.URL
	err := row.Scan(&lurl)
	if err != nil {
		// TODO: change the return value witht another entity.URL
		return surl, fmt.Errorf("cannot return this url when scanning: %w\n", err)
	}
	return lurl, nil
}

func (p Postgres) SetShortURL(ctx context.Context, lurl entity.URL) (entity.URL, error) {
	res, err := p.db.ExecContext(ctx, "insert into ulrs (key, url) values ($1, $2)", lurl.Key, lurl.LURL)
	if err != nil {
		// TODO: change the return value witht another entity.URL
		return lurl, fmt.Errorf("cannot set this url into db: %w\n", err)
	}

	id, err := res.LastInsertId()
	if err != nil {
		// TODO: change the return value witht another entity.URL
		return lurl, fmt.Errorf("cannot get id generated by the db: %w\n", err)
	}
	lurl.ID = uint(id)
	// TODO: change the return value witht another entity.URL
	return lurl, nil
}

func (p Postgres) IsURLInDB(ctx context.Context, url string) (entity.URL, error) {
	row, err := p.db.QueryContext(ctx, "select key from urls where url=$1", url)
	if err != nil {
		return entity.URL{}, fmt.Errorf("cannot get key by this url: %w\n", err)
	}

	var res entity.URL

	err = row.Scan(&res)
	if err != nil {
		return entity.URL{}, fmt.Errorf("error while scanning the result: %w\n", err)
	}

	return res, nil
}

func (p Postgres) IsKeyInDB(ctx context.Context, key string) (entity.URL, error) {
	row, err := p.db.QueryContext(ctx, "select url from urls where key=$1", key)
	if err != nil {
		return entity.URL{}, fmt.Errorf("cannot get url by this key: %w\n", err)
	}

	var res entity.URL

	err = row.Scan(&res)
	if err != nil {
		return entity.URL{}, fmt.Errorf("error while scanning the result: %w\n", err)
	}

	return res, nil
}
